# Generated by Django 5.2 on 2025-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_relationship_is_former'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='relationship_is_former',
            field=models.BooleanField(default=False, verbose_name='Former relationship?'),
        ),
    ]
