# Generated by Django 5.2 on 2025-06-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_relationship_is_former'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='core.skill'),
        ),
    ]
