# Generated by Django 5.2 on 2025-07-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_keyword_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current_education',
            field=models.BooleanField(default=False, verbose_name='Currently attend here'),
        ),
    ]
