# Generated by Django 5.2 on 2025-07-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_education_is_current_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='core.job'),
        ),
    ]
