# Generated by Django 5.2 on 2025-07-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_highlight_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position_supplement',
            field=models.CharField(blank=True, help_text='Used when official position title not clear', max_length=125, null=True),
        ),
    ]
