# Generated by Django 5.2 on 2025-07-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_position_supplement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='display_name',
            new_name='public_display_name',
        ),
    ]
