# Generated by Django 5.2 on 2025-07-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_display_name_basics_public_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, help_text='Official position title', max_length=125, null=True),
        ),
    ]
