# Generated by Django 5.2 on 2025-07-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='basics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='core.basics'),
        ),
    ]
