# Generated by Django 5.2 on 2025-07-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_socialprofile_basics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='basics_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='basics',
            old_name='basics_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='basics',
            old_name='basics_website',
            new_name='website',
        ),
    ]
