# Generated by Django 5.2 on 2025-07-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_basics_email_basics_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skills with keywords', 'verbose_name_plural': 'Skills with keywords'},
        ),
    ]
