# Generated by Django 5.2 on 2025-07-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_skill_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
