# Generated by Django 5.2 on 2025-07-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_skill_icon'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='education',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='check_start_date_educ', violation_error_message='End date must be after start date'),
        ),
    ]
