# Generated by Django 5.2 on 2025-08-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_address_address_line_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrelationship',
            name='description',
            field=models.CharField(max_length=45),
        ),
    ]
