# Generated by Django 5.2 on 2025-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='emp_type',
            field=models.CharField(max_length=45),
        ),
    ]
