# Generated by Django 5.2 on 2025-08-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_employmenttype_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(help_text='Official position title', max_length=125),
        ),
    ]
