# Generated by Django 5.2 on 2025-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
