# Generated by Django 5.2 on 2025-08-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_socialprofile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='is_current_education',
            new_name='is_current',
        ),
    ]
