# Generated by Django 5.2 on 2025-08-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_is_current_education_education_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='is_current_position',
            new_name='is_current',
        ),
    ]
