"""
Django settings for mch_site project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
from pathlib import Path
from decouple import config
from django.urls import reverse_lazy


'''NOTE: the following should be done via the reverse proxy server, e.g. Nginx
 - rate limiting
 - restrict admin by IP
'''
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# check if only deploying locally
LOCAL = config('LOCAL', default=False, cast=bool)

# Application definition

INSTALLED_APPS = [
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS += [
    'django_distill',
    'djmoney',
    "django_extensions",
    "django_icons",
    'core.apps.CoreConfig',
    'common.apps.CommonConfig',
    'portfolio.apps.PortfolioConfig',
    'reports.apps.ReportsConfig',
    'resumes.apps.ResumesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mch_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mch_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'mchdb_local.sqlite3',
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# https://learndjango.com/tutorials/django-static-files
# pre-production settings - add Whitenoise later when go to production
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings for ERD
GRAPH_MODELS = {
    'all_applications': True,
    'group_models': True,
}

FIXTURE_DIRS = [BASE_DIR / "fixtures"]

# https://docs.djangoproject.com/en/5.2/ref/settings/#login-url
LOGIN_URL = reverse_lazy('admin:index')

# MAYBE add project icon
# https://fontawesome.com/icons/diagram-project?s=solid
DJANGO_ICONS = {
    "ICONS": {
        "about": {"name": "fa-solid fa-user"},
        "projects": {"name": "fa-solid fa-code-branch"},
        "skills": {"name": "fa-regular fa-lightbulb"},
        "contact": {"name": "fa-solid fa-envelopes-bulk"},
        "star": {"name": "fa-solid fa-star"},
        "eye": {"name": "fa-solid fa-eye"},
        "globe": {"name": "fa-solid fa-globe"},
        "email": {"name": "fa-solid fa-envelope"},
        "linkedin": {"name": "fa-brands fa-square-linkedin"},
        "github": {"name": "fa-brands fa-square-github"},
        "x": {"name": "fa-brands fa-x-twitter"},

    },
}

# Logging setup
# NOTE: only used for logging the contact form. set up for use in dev & production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': config('LOGGING_LEVEL', default='INFO'),
            'class': 'logging.FileHandler',
            'filename': config('LOGGING_FILENAME', default='logs/site.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': config('LOGGING_LEVEL', default='INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': config('LOGGING_LEVEL', default='INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': config('LOGGING_LEVEL', default='INFO'),
            'propagate': True,
        },
    },
}

# have to have this here so processes during setup. otherwise, app not loaded yet errors.
# Parse ADMINS from .env


def parse_admins(admins_str):
    return [
        tuple(admin.strip().split(':', 1))
        for admin in admins_str.split(',')
        if ':' in admin
    ]


# Only apply the following settings if DEBUG is False (for production)
if not DEBUG:

    # Security settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Clickjacking Protection
    X_FRAME_OPTIONS = 'DENY'

    # Production email backend
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST')
    EMAIL_PORT = config('EMAIL_PORT', cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)

    # Admin stuff
    ADMINS = parse_admins(config('ADMINS', default=''))
    MANAGERS = ADMINS

    SERVER_EMAIL = config('SERVER_EMAIL')


# Development email backend (console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Distill settings
# if publishing in current repo:
# DISTILL_DIR = BASE_DIR / "docs"
# if publishing to separate repo:
DISTILL_DIR = config('DISTILL_DIR')

# skip
# see https://github.com/meeb/django-distill/?tab=readme-ov-file#optional-configuration-settings

# https://stackoverflow.com/questions/31352317/how-to-pass-a-list-as-an-environment-variable
# Posted by Martin Thoma, modified by community. See post 'Timeline' for change history
# Retrieved 2025-12-20, License - CC BY-SA 4.0
# use json loads to load the list from .env
DISTILL_SKIP_STATICFILES_DIRS = json.loads(
    config('DISTILL_SKIP_STATICFILES_DIRS'))

STATIC_SITE_REPO_DIR = config('STATIC_SITE_REPO_DIR')
