# Generated by Django 5.2 on 2025-07-20 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_remove_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='resume', max_length=125)),
                ('professional_profile', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('basics', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='core.basics')),
                ('educations', models.ManyToManyField(blank=True, to='core.education')),
                ('jobs', models.ManyToManyField(blank=True, to='core.job')),
                ('keywords', models.ManyToManyField(blank=True, to='core.keyword')),
                ('social_profiles', models.ManyToManyField(blank=True, to='core.socialprofile')),
            ],
        ),
    ]
