# Generated by Django 5.2 on 2025-06-01 16:47

import reports.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBackgroundCheck',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Background Check',
                'verbose_name_plural': 'Contact Background Check',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(reports.models.ContactPropertiesMixin, 'core.contact'),
        ),
        migrations.CreateModel(
            name='ContactReferences',
            fields=[
            ],
            options={
                'verbose_name': 'Contact References',
                'verbose_name_plural': 'Contact References',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(reports.models.ContactPropertiesMixin, 'core.contact'),
        ),
        migrations.CreateModel(
            name='EducHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.education',),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.job',),
        ),
    ]
