# Generated by Django 5.2 on 2025-06-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_contact_relationship_is_former'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contact',),
        ),
        migrations.CreateModel(
            name='EducHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.education',),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.job',),
        ),
    ]
