# Generated by Django 5.2 on 2025-08-16 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0026_rename_is_current_position_job_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Navigation', max_length=50)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menu',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=125)),
                ('cite_href', models.URLField(blank=True, max_length=255, null=True)),
                ('cite_name', models.CharField(blank=True, max_length=125, null=True)),
                ('quote_image', models.ImageField(blank=True, null=True, upload_to='quote/')),
                ('quote_image_alt_text', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/Site Name', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='seo/')),
                ('og_type', models.CharField(default='website', help_text='See object types in https://ogp.me/', max_length=120)),
                ('og_imgurl', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SEO Config',
                'verbose_name_plural': 'SEO Config',
            },
        ),
        migrations.CreateModel(
            name='TwitterCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Twitter Card Type',
                'verbose_name_plural': 'Twitter Card Types',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('slug', models.SlugField(help_text='Auto-filled from title only on creation; editable afterward but not auto-updated.', max_length=10, unique=True)),
                ('order', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('navigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='portfolio.navigation')),
            ],
            options={
                'verbose_name': 'Nav Item',
                'verbose_name_plural': 'Nav Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Can be an animated typing introduction.', max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=25, null=True)),
                ('visual', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('visual_alt_text', models.CharField(blank=True, max_length=20, null=True)),
                ('cta_nav_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_hero', to='portfolio.navitem')),
            ],
            options={
                'verbose_name': 'About Hero',
                'verbose_name_plural': 'About Hero',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_hero', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='portfolio.abouthero')),
                ('basics', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='core.basics')),
                ('keywords', models.ManyToManyField(blank=True, related_name='portfolio', to='core.keyword')),
                ('navigation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='portfolio.navigation')),
                ('social_profiles', models.ManyToManyField(blank=True, related_name='portfolio', to='core.socialprofile')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='portfolio.quote')),
                ('seo_config', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='portfolio.seoconfig')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.AddField(
            model_name='seoconfig',
            name='twitter_card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.twittercardtype'),
        ),
    ]
