# Generated by Django 5.2 on 2025-08-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthero',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
