# Generated by Django 5.2 on 2025-08-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_abouthero_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='portfolio.quote'),
        ),
    ]
