# Generated by Django 5.2 on 2025-09-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_quote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthero',
            name='cta_nav_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_hero', to='portfolio.navitem', verbose_name='CTA nav item'),
        ),
        migrations.AlterField(
            model_name='abouthero',
            name='cta_text',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CTA text'),
        ),
    ]
