# Generated by Django 5.2 on 2025-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='64x64 PNG', upload_to='seo/'),
        ),
    ]
