# Generated by Django 5.2 on 2025-09-21 19:43

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_seoconfig_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='max size: 64x64, file types: ICO,SVG, PNG', upload_to='seo/', validators=[common.utils.validate_favicon]),
        ),
    ]
