# Generated by Django 5.2 on 2025-09-21 20:55

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_seoconfig_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoconfig',
            name='favicon',
            field=models.FileField(blank=True, help_text='sizes: 32x32, 64x64. file types: PNG', upload_to='seo/', validators=[common.utils.validate_favicon]),
        ),
    ]
