# Generated by Django 5.2 on 2025-12-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_seoconfig_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Portfolio is active?'),
        ),
    ]
