# Generated by Django 5.2 on 2025-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='contact_cta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
